export const categories = [
  "All",
  "Tents & Canopy",
  "Lighting",
  "Tables & Chairs",
  "Audio & Sound",
  "Decoration",
  "Stage & Platform",
  "Catering Equipment",
  "Photography",
  "Services",
];

export const services = [
  "Event Supplies",
  "Equipment Rental",
  "Event Decoration",
  "Sound & Lighting",
  "Full Event Management",
  "Tent & Canopy",
  "Table & Chair Rental",
  "Stage Setup",
  "Catering Equipment",
  "Photo Booth",
  "Emcee & Entertainment",
  "Setup & Teardown",
];

export interface Product {
  slug: string;
  name: string;
  subtitle: string;
  description: string;
  category: string;
  price: number;
  image: string;
  includes: string[];
}

export const products: Product[] = [
  // Tents & Canopy
  {
    slug: "premium-tent-10x10",
    name: "Premium Tent 10x10",
    subtitle: "Heavy duty canopy with sidewalls",
    description: "Our premium 10x10 heavy duty canopy is perfect for small to medium outdoor events. Built with a sturdy steel frame and waterproof PVC roof, this tent provides reliable shelter in any weather. Comes complete with removable sidewalls for flexible ventilation and privacy options.",
    category: "Tents & Canopy",
    price: 500,
    image: "https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=400&h=400&fit=crop",
    includes: ["10x10 ft steel frame canopy", "Waterproof PVC roof cover", "4x removable sidewalls", "Ground stakes and tie-downs", "Delivery and setup"],
  },
  {
    slug: "garden-marquee",
    name: "Garden Marquee",
    subtitle: "Transparent marquee for outdoor events",
    description: "Elegant transparent garden marquee that creates a stunning see-through effect for outdoor events. Perfect for garden weddings, engagement parties, and intimate gatherings. The clear panels allow natural light while protecting guests from weather.",
    category: "Tents & Canopy",
    price: 350,
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=400&h=400&fit=crop",
    includes: ["Transparent PVC marquee", "Steel frame structure", "Entrance draping", "Ground anchoring system", "Setup and teardown"],
  },
  {
    slug: "canopy-20x20",
    name: "Canopy 20x20",
    subtitle: "Large canopy for 100+ pax events",
    description: "Our largest canopy option, ideal for big events like weddings, corporate dinners, and community gatherings. The 20x20 ft coverage comfortably fits 10-15 round tables and can accommodate over 100 guests. Heavy duty construction ensures stability.",
    category: "Tents & Canopy",
    price: 400,
    image: "https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=400&h=400&fit=crop",
    includes: ["20x20 ft heavy duty canopy", "Reinforced steel frame", "Waterproof roof", "Optional sidewalls", "Professional setup crew"],
  },
  {
    slug: "a-frame-tent",
    name: "A-Frame Tent",
    subtitle: "Classic A-frame tent 10x20 ft",
    description: "The classic A-frame tent is a timeless choice for outdoor events. With its distinctive peaked roof design, this 10x20 ft tent offers excellent headroom and a spacious interior. Popular for food stalls, registration areas, and VIP sections.",
    category: "Tents & Canopy",
    price: 600,
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=400&h=400&fit=crop",
    includes: ["10x20 ft A-frame tent", "White PVC roof cover", "Steel pole frame", "Sidewall options", "Delivery and installation"],
  },
  {
    slug: "pyramid-tent",
    name: "Pyramid Tent",
    subtitle: "Elegant pyramid canopy 15x15 ft",
    description: "Make a statement with our elegant pyramid tent. The distinctive high-peak design creates a luxurious look perfect for upscale events, VIP lounges, and wedding receptions. The 15x15 ft footprint provides ample space with a dramatic ceiling height.",
    category: "Tents & Canopy",
    price: 750,
    image: "https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=400&h=400&fit=crop",
    includes: ["15x15 ft pyramid canopy", "High-peak center pole design", "Premium white fabric", "Full sidewall set", "Professional installation"],
  },

  // Lighting
  {
    slug: "led-stage-lighting",
    name: "LED Stage Lighting",
    subtitle: "Full RGB par lights with DMX control",
    description: "Professional LED stage lighting package with full RGB color mixing capabilities. Controlled via DMX for precise color and intensity adjustments. Perfect for stages, dance floors, and event spaces that need dynamic lighting effects.",
    category: "Lighting",
    price: 300,
    image: "https://images.unsplash.com/photo-1504509546545-e000b4a62425?w=400&h=400&fit=crop",
    includes: ["8x LED par lights", "DMX controller", "Lighting stands", "All cables and connectors", "Setup by lighting technician"],
  },
  {
    slug: "fairy-light-set",
    name: "Fairy Light Set",
    subtitle: "Warm white string lights, 50m length",
    description: "Create a magical atmosphere with our warm white fairy light set. At 50 meters total length, these lights are perfect for draping across ceilings, wrapping around pillars, or creating a canopy of lights. Ideal for weddings, dinners, and romantic settings.",
    category: "Lighting",
    price: 80,
    image: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=400&h=400&fit=crop",
    includes: ["50m warm white fairy lights", "Extension cables", "Mounting clips and hooks", "Spare bulbs"],
  },
  {
    slug: "moving-head-lights",
    name: "Moving Head Lights",
    subtitle: "2x moving head spot lights with stand",
    description: "Add excitement to your event with our moving head spot lights. These professional-grade lights produce sharp beams that sweep and rotate across the venue, creating a dynamic club or concert atmosphere. Perfect for stages, dance floors, and entertainment events.",
    category: "Lighting",
    price: 450,
    image: "https://images.unsplash.com/photo-1504509546545-e000b4a62425?w=400&h=400&fit=crop",
    includes: ["2x moving head spot lights", "Heavy duty stands", "DMX controller", "Safety cables", "Technician for setup"],
  },
  {
    slug: "uplighting-set",
    name: "Uplighting Set",
    subtitle: "10x LED uplights for wall wash effect",
    description: "Transform any venue with our LED uplighting set. Place these lights at the base of walls, pillars, or behind backdrops to create beautiful color washes. Fully customizable colors to match your event theme. Battery-powered for wireless placement anywhere.",
    category: "Lighting",
    price: 200,
    image: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=400&h=400&fit=crop",
    includes: ["10x wireless LED uplights", "Remote controller", "Charging cables", "Color preset guide"],
  },
  {
    slug: "chandelier-rental",
    name: "Chandelier Rental",
    subtitle: "Crystal chandelier with rigging",
    description: "Add elegance and sophistication to your event with our crystal chandelier. This stunning centerpiece creates a luxurious ambiance perfect for wedding receptions, gala dinners, and formal events. Includes professional rigging and installation.",
    category: "Lighting",
    price: 350,
    image: "https://images.unsplash.com/photo-1504509546545-e000b4a62425?w=400&h=400&fit=crop",
    includes: ["Crystal chandelier", "Rigging hardware", "Dimmer control", "Professional installation", "Removal after event"],
  },

  // Tables & Chairs
  {
    slug: "round-table-setup",
    name: "Round Table Setup",
    subtitle: "Round table with linen and centerpiece",
    description: "Complete round table setup ready for your guests. Each table comfortably seats 8-10 people and comes dressed with premium linen tablecloth and a simple centerpiece. Perfect for wedding receptions, corporate dinners, and formal events.",
    category: "Tables & Chairs",
    price: 150,
    image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400&h=400&fit=crop",
    includes: ["5ft round table", "Floor-length linen tablecloth", "Table runner", "Simple centerpiece", "Setup included"],
  },
  {
    slug: "tiffany-chair-set",
    name: "Tiffany Chair Set",
    subtitle: "Tiffany chairs with cushion, set of 10",
    description: "Elegant Tiffany chairs (also known as Chiavari chairs) are the gold standard for formal events. These beautiful chairs add a touch of class to any setting. Available in gold, silver, or white. Each chair comes with a matching cushion for comfort.",
    category: "Tables & Chairs",
    price: 200,
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?w=400&h=400&fit=crop",
    includes: ["10x Tiffany/Chiavari chairs", "Matching seat cushions", "Choice of gold/silver/white", "Delivery and collection"],
  },
  {
    slug: "banquet-table",
    name: "Banquet Table",
    subtitle: "6ft rectangular banquet table with cloth",
    description: "Standard 6ft rectangular banquet table suitable for buffet lines, registration desks, product displays, or dining. Comes with a fitted tablecloth for a clean, professional look. Sturdy folding design for easy placement.",
    category: "Tables & Chairs",
    price: 80,
    image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400&h=400&fit=crop",
    includes: ["6ft rectangular folding table", "Fitted tablecloth", "Table skirting"],
  },
  {
    slug: "plastic-chair-set",
    name: "Plastic Chair Set",
    subtitle: "White plastic chairs, set of 10",
    description: "Practical and affordable white plastic chairs suitable for any event. Lightweight, stackable, and easy to arrange. Ideal for outdoor events, casual gatherings, meetings, and large-scale events where quantity is needed.",
    category: "Tables & Chairs",
    price: 50,
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?w=400&h=400&fit=crop",
    includes: ["10x white plastic chairs", "Delivery and collection"],
  },
  {
    slug: "cocktail-table",
    name: "Cocktail Table",
    subtitle: "High cocktail table with spandex cover",
    description: "Stylish high cocktail tables perfect for networking events, cocktail receptions, and standing gatherings. Each table comes with a fitted spandex cover for a sleek, modern look. Available in black or white covers.",
    category: "Tables & Chairs",
    price: 120,
    image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400&h=400&fit=crop",
    includes: ["High cocktail table", "Spandex cover (black or white)", "Delivery and collection"],
  },

  // Audio & Sound
  {
    slug: "sound-system-pro",
    name: "Sound System Pro",
    subtitle: "2x speakers, mixer, and wireless mic",
    description: "Professional sound system package suitable for medium to large events up to 300 pax. Delivers clear, powerful audio for speeches, music, and performances. Comes with a mixer for live sound control and wireless microphones for presenters.",
    category: "Audio & Sound",
    price: 450,
    image: "https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=400&h=400&fit=crop",
    includes: ["2x 15-inch powered speakers", "Audio mixer", "2x wireless handheld mics", "Speaker stands", "All cables", "Sound check included"],
  },
  {
    slug: "wireless-mic-set",
    name: "Wireless Mic Set",
    subtitle: "2x handheld wireless microphones",
    description: "High-quality wireless handheld microphones for clear voice projection. Perfect as an add-on to existing sound systems or for small venue use. Anti-interference technology ensures stable, drop-free audio throughout your event.",
    category: "Audio & Sound",
    price: 120,
    image: "https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=400&h=400&fit=crop",
    includes: ["2x wireless handheld microphones", "Receiver unit", "Batteries", "Audio cable"],
  },
  {
    slug: "pa-system-basic",
    name: "PA System Basic",
    subtitle: "Basic PA with 2 speakers for small events",
    description: "Compact PA system ideal for small events, meetings, and gatherings up to 100 pax. Easy to set up and operate with Bluetooth connectivity for music playback. Great value for smaller venues and casual events.",
    category: "Audio & Sound",
    price: 250,
    image: "https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=400&h=400&fit=crop",
    includes: ["2x 12-inch powered speakers", "1x wireless mic", "Bluetooth receiver", "Speaker stands", "Setup included"],
  },
  {
    slug: "dj-equipment-set",
    name: "DJ Equipment Set",
    subtitle: "DJ controller, mixer, and monitor speakers",
    description: "Complete DJ equipment setup for parties, weddings, and entertainment events. Professional-grade controller and mixer with monitor speakers for the DJ booth. Just add a DJ and you're ready to go — or we can provide one too.",
    category: "Audio & Sound",
    price: 600,
    image: "https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=400&h=400&fit=crop",
    includes: ["DJ controller", "Audio mixer", "2x monitor speakers", "Headphones", "All cables and stands", "Setup and testing"],
  },
  {
    slug: "lapel-mic-set",
    name: "Lapel Mic Set",
    subtitle: "Wireless lapel mic for presentations",
    description: "Discreet wireless lapel microphone perfect for presenters, emcees, and speakers who need hands-free operation. Clips onto clothing and provides clear audio pickup. Ideal for corporate presentations, seminars, and formal ceremonies.",
    category: "Audio & Sound",
    price: 80,
    image: "https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=400&h=400&fit=crop",
    includes: ["Wireless lapel microphone", "Bodypack transmitter", "Receiver unit", "Spare battery"],
  },

  // Decoration
  {
    slug: "flower-backdrop",
    name: "Flower Backdrop",
    subtitle: "Artificial flower wall 8x8 ft",
    description: "Stunning artificial flower wall backdrop that creates a beautiful photo opportunity at any event. The 8x8 ft panel features high-quality silk flowers in a lush arrangement. Perfect behind the pelamin, dessert table, or as a photo wall for guests.",
    category: "Decoration",
    price: 250,
    image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=400&h=400&fit=crop",
    includes: ["8x8 ft flower wall panel", "Support frame and stand", "Setup and teardown", "Custom color options available"],
  },
  {
    slug: "balloon-arch",
    name: "Balloon Arch",
    subtitle: "Custom color balloon arch for entrance",
    description: "Eye-catching balloon arch to welcome guests at your event entrance. Custom colors to match your event theme. Our team will design and construct the arch on-site for a perfect fit. Great for birthdays, openings, and celebrations.",
    category: "Decoration",
    price: 180,
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&h=400&fit=crop",
    includes: ["Custom color balloon arch", "Frame structure", "On-site construction", "Removal after event"],
  },
  {
    slug: "red-carpet-setup",
    name: "Red Carpet Setup",
    subtitle: "Red carpet with stanchions and ropes",
    description: "Roll out the red carpet for a VIP experience. Our red carpet setup includes premium velvet stanchions and ropes to create a grand entrance for your guests. Perfect for gala dinners, award ceremonies, corporate launches, and formal events.",
    category: "Decoration",
    price: 150,
    image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=400&h=400&fit=crop",
    includes: ["Red carpet (customizable length)", "6x velvet stanchions", "Velvet ropes", "Setup included"],
  },
  {
    slug: "pelamin-package",
    name: "Pelamin Package",
    subtitle: "Complete wedding pelamin with deco",
    description: "Our signature wedding pelamin package includes a beautifully designed dais with full decoration. Customizable to match your wedding theme and colors. Our experienced team handles everything from design to setup so the bride and groom can relax.",
    category: "Decoration",
    price: 1500,
    image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400&h=400&fit=crop",
    includes: ["Custom pelamin/dais design", "Fresh or artificial flowers", "Fabric draping", "Lighting for pelamin", "Sofa set for bride & groom", "Full setup and teardown"],
  },
  {
    slug: "table-centerpiece",
    name: "Table Centerpiece",
    subtitle: "Fresh flower arrangement per table",
    description: "Elegant fresh flower centerpiece arrangement to dress up your dining tables. Each arrangement is carefully crafted to complement your event theme. Price is per table. Minimum order of 5 tables required.",
    category: "Decoration",
    price: 60,
    image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=400&h=400&fit=crop",
    includes: ["Fresh flower arrangement", "Vase or container", "Delivery and placement", "Minimum 5 tables"],
  },

  // Stage & Platform
  {
    slug: "stage-8x12",
    name: "Stage 8x12 ft",
    subtitle: "Portable stage with skirting",
    description: "Portable modular stage perfect for speeches, performances, and presentations. The 8x12 ft platform provides enough space for a small band, speaker podium, or ceremony area. Includes professional skirting for a clean finished look.",
    category: "Stage & Platform",
    price: 500,
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&h=400&fit=crop",
    includes: ["8x12 ft modular stage", "Adjustable legs (1-3 ft height)", "Stage skirting", "Steps with handrail", "Setup by crew"],
  },
  {
    slug: "stage-12x16",
    name: "Stage 12x16 ft",
    subtitle: "Large stage platform with steps",
    description: "Our large stage platform is designed for bigger events — concerts, award ceremonies, fashion shows, and corporate presentations. The 12x16 ft area provides ample space for performers, equipment, and backdrop setups.",
    category: "Stage & Platform",
    price: 800,
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&h=400&fit=crop",
    includes: ["12x16 ft modular stage", "Adjustable legs (1-4 ft height)", "Full skirting", "Double-width steps", "Safety railings", "Professional setup crew"],
  },
  {
    slug: "runway-platform",
    name: "Runway Platform",
    subtitle: "Fashion runway 4x20 ft with carpet",
    description: "Sleek runway platform for fashion shows, product launches, and special presentations. The 4x20 ft narrow platform creates a dramatic walkway for models or presenters. Includes carpet covering for a polished finish.",
    category: "Stage & Platform",
    price: 600,
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&h=400&fit=crop",
    includes: ["4x20 ft runway platform", "Carpet covering", "Stage skirting", "End platform option", "Setup and teardown"],
  },
  {
    slug: "podium-lectern",
    name: "Podium / Lectern",
    subtitle: "Wooden podium with mic stand",
    description: "Professional wooden podium for speeches and presentations. Features a slanted reading surface, internal shelf, and built-in mic stand mount. Gives a polished, formal look to any speaking engagement.",
    category: "Stage & Platform",
    price: 100,
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&h=400&fit=crop",
    includes: ["Wooden podium/lectern", "Mic stand mount", "Reading light", "Delivery and collection"],
  },

  // Catering Equipment
  {
    slug: "chafing-dish-set",
    name: "Chafing Dish Set",
    subtitle: "Stainless steel chafing dish, set of 5",
    description: "Keep your food warm and presentable with our stainless steel chafing dish set. Essential for buffet-style catering at weddings, corporate events, and parties. Each dish includes a fuel holder to maintain temperature throughout the event.",
    category: "Catering Equipment",
    price: 100,
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?w=400&h=400&fit=crop",
    includes: ["5x stainless steel chafing dishes", "Water pans", "Food pans", "Fuel holders and fuel", "Serving spoons"],
  },
  {
    slug: "drink-dispenser",
    name: "Drink Dispenser",
    subtitle: "Glass beverage dispenser 8L, set of 3",
    description: "Elegant glass beverage dispensers for self-serve drink stations. Perfect for serving infused water, juice, iced tea, or lemonade. The 8-liter capacity keeps drinks flowing throughout your event. Includes a stand for easy dispensing.",
    category: "Catering Equipment",
    price: 60,
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?w=400&h=400&fit=crop",
    includes: ["3x 8L glass dispensers", "Metal stands", "Drip trays"],
  },
  {
    slug: "buffet-table-setup",
    name: "Buffet Table Setup",
    subtitle: "Full buffet line with skirting and utensils",
    description: "Complete buffet line setup for catered events. Includes everything needed to present food professionally — from the tables and skirting to serving utensils and sneeze guards. Just add the food and your buffet is ready to serve.",
    category: "Catering Equipment",
    price: 300,
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?w=400&h=400&fit=crop",
    includes: ["3x buffet tables with skirting", "Chafing dishes", "Serving utensils", "Sneeze guards", "Table labels", "Setup included"],
  },
  {
    slug: "ice-cream-machine",
    name: "Ice Cream Machine",
    subtitle: "Soft serve ice cream machine rental",
    description: "Fun soft serve ice cream machine that dispenses delicious ice cream for your guests. A crowd favorite at weddings, birthday parties, and corporate events. We provide the machine, mix, and cones — an operator is included to serve your guests.",
    category: "Catering Equipment",
    price: 350,
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?w=400&h=400&fit=crop",
    includes: ["Soft serve ice cream machine", "Ice cream mix (vanilla & chocolate)", "Cones and cups", "Operator for 4 hours", "Setup and cleanup"],
  },

  // Photography
  {
    slug: "photo-booth",
    name: "Photo Booth",
    subtitle: "Instant print photo booth with props",
    description: "Fun instant-print photo booth that guests love. Features a high-quality DSLR camera, professional lighting, and a selection of fun props. Photos are printed instantly as keepsakes. Includes a friendly booth attendant to keep things running smoothly.",
    category: "Photography",
    price: 800,
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=400&h=400&fit=crop",
    includes: ["Photo booth setup", "DSLR camera and lighting", "Instant photo printer", "Props and accessories", "Custom photo template", "Booth attendant (4 hours)", "Unlimited prints"],
  },
  {
    slug: "360-video-booth",
    name: "360 Video Booth",
    subtitle: "360 degree video spinner booth",
    description: "The trending 360 video booth captures guests on a spinning platform for slow-motion 360-degree videos. Guests receive their video instantly via QR code to share on social media. A viral hit at any event — guaranteed to get people talking.",
    category: "Photography",
    price: 1200,
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=400&h=400&fit=crop",
    includes: ["360 spinner platform", "HD camera system", "LED ring light", "Instant video sharing via QR", "Custom video overlay", "Operator (4 hours)"],
  },
  {
    slug: "ring-light-setup",
    name: "Ring Light Setup",
    subtitle: "LED ring light with tripod for selfie station",
    description: "Simple and effective selfie station setup with a professional LED ring light on a tripod. Place it near a backdrop or photo wall and let guests take their own flattering photos. Budget-friendly alternative to a full photo booth.",
    category: "Photography",
    price: 80,
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=400&h=400&fit=crop",
    includes: ["18-inch LED ring light", "Adjustable tripod stand", "Phone holder mount", "Carry case"],
  },

  // Services
  {
    slug: "event-coordinator",
    name: "Event Coordinator",
    subtitle: "Professional event coordinator for the day",
    description: "Our experienced event coordinator will manage your event from start to finish on the day itself. They handle vendor coordination, timeline management, guest flow, and troubleshooting so you can relax and enjoy your event. Available for full-day or half-day bookings.",
    category: "Services",
    price: 500,
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400&h=400&fit=crop",
    includes: ["Professional event coordinator", "Day-of timeline management", "Vendor coordination", "Guest flow management", "Problem solving and backup plans", "Full day (up to 10 hours)"],
  },
  {
    slug: "full-event-management",
    name: "Full Event Management",
    subtitle: "End-to-end planning and execution",
    description: "Let us handle everything from planning to execution. Our full event management service covers concept development, vendor sourcing, budget management, logistics, and on-the-day coordination. Ideal for those who want a stress-free event experience.",
    category: "Services",
    price: 3000,
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400&h=400&fit=crop",
    includes: ["Event concept and planning", "Vendor sourcing and management", "Budget planning and tracking", "Timeline and logistics", "Day-of coordination", "Post-event wrap up", "Dedicated event manager"],
  },
  {
    slug: "setup-teardown",
    name: "Setup & Teardown",
    subtitle: "Crew for event setup and teardown",
    description: "Professional crew to handle the physical setup and teardown of your event. Our team arrives early to arrange furniture, equipment, and decorations according to your floor plan, and returns after the event to pack everything down efficiently.",
    category: "Services",
    price: 300,
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400&h=400&fit=crop",
    includes: ["Setup crew (3-5 persons)", "Pre-event arrangement", "Post-event teardown", "Equipment handling", "Up to 8 hours"],
  },
  {
    slug: "emcee-host",
    name: "Emcee / Host",
    subtitle: "Professional bilingual emcee",
    description: "Engage your guests with our professional bilingual emcee. Experienced in hosting weddings, corporate events, product launches, and formal ceremonies. Fluent in Malay and English with the ability to adapt tone and style to match your event.",
    category: "Services",
    price: 600,
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400&h=400&fit=crop",
    includes: ["Professional bilingual emcee", "Pre-event briefing", "Script preparation", "Up to 5 hours", "Malay and English"],
  },
  {
    slug: "live-band",
    name: "Live Band",
    subtitle: "4-piece live band for 2 hours",
    description: "Live music brings energy and atmosphere to any event. Our 4-piece band performs a mix of popular hits, jazz, and local favorites. Perfect for wedding dinners, corporate events, and private parties. Song requests welcome with advance notice.",
    category: "Services",
    price: 2000,
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400&h=400&fit=crop",
    includes: ["4-piece live band", "2 hours performance", "Own PA system", "Song request list", "2x 45-min sets with break", "Setup and sound check"],
  },
];
